# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95071fa6d44aa0fda582aab6e50dacd1e1640d5b522bc6170efd3d159b07af8f612e690e13923868c6e7c7c34f0058e0b765b709b44709d3123c6658fb78848

test:
  secret_key_base: 6c772494fc750c7d2185108dd0243689afd0d59ec42c29530aaae7fbab7bbf958b61137e9056a7403d1c544c2157d76a8a075a9a25071aa9b05e69ecfe681470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
